# Site settings
title: Chowdown
email: patrick@freebsd.org
description: The plain text recipe database for hackers
domain: patrickgardella.github.io
url: https://patrickgardella.github.io
baseurl: 
twitter_username: patrickgardella
github_username:  patrickgardella

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

